version: "2.1"
services:
  plex-recommendations:
    image: 007trains/plex-recommendations-ai:latest
    container_name: plex-recommendations
    environment:
      - PLEX_URL=<local plex url>
      - PLEX_TOKEN=<plex token>
      - OPEN_AI_KEY=<open ai key>
      - OPEN_AI_VERSION=<open ai version>
      - LIBRARY_NAME=<library name>
      - COLLECTION_TITLE=<title>
      - HISTORY_AMOUNT=<amount>
      - RECOMMENDED_AMOUNT=<amount>
      - MINIMUM_AMOUNT=<amount>
      - SECONDS_TO_WAIT=<amount>
    restart: unless-stopped
